print("hello M.6/14")
print("name=Jirawat Phutphong")
print("nickname=Champ")
print("birthday=04/05/2005")
print("age=17")
print("bloodtype=A")
print("phone number=0983683100")
print("hobby=play game")
print("my favorite color=black")
print("my favorite subject=math physics")
print("my favorite animal=dog")
# ชื่อ จิรวัฒน์ ผุดผ่อง เลขที่ 2